trigger:
  branches:
    include:
      - main

variables:
  - group: devgiglio-env
  - group: devgiglio-secrets
  - group: envs-cloudflare
  - name: APP_NAME
    value: chat-universal-server
  - name: STACK
    value: node
  - name: DEPLOY_ENABLED
    value: "true"
  - name: TEST_ENABLED
    value: "true"
  - name: DOCS_ENABLED
    value: "false"

pool:
  name: Default

resources:
  repositories:
    - repository: templates
      type: github
      name: gipierogiglio-prog/devgiglio-pipelines
      ref: main
      endpoint: gipierogiglio-prog

stages:
  - template: stages/build/node-build.yml@templates
    parameters:
      appName: chat-universal-server

  - template: stages/deploy/deploy-vps.yml@templates
    parameters:
      appName: chat-universal-server
